### ISSUE TITLE
Recent library recommendation

### ISSUE THREAD

**Issue by artshcherbina** [gau-nernst/centernet-lightning#5]
Hello!

Thank you for your work.
In the other issue, you've mentioned, that the library is not maintained anymore.

I'm curious, if you are still working with detection task?
Is your library still comparable in terms of model accuracy or there is better library/framework for this task?

**Comment by gau-nernst** [comment]
I'm no longer working on object detection. Haven't been looking at latest object detection works now, but I think https://github.com/ultralytics/ultralytics is the easiest to get something reasonably good.

**Comment by artshcherbina** [comment]
Thank you!
Nevertheless, I would like to train a model with your code.
It is well organized and simpler to extend.

**Comment by gau-nernst** [comment]
Thank you for your kind words. Indeed all modern detection frameworks are very complex (perhaps because getting fast and accurate detection results is necessarily complex). Recently I had to build a document corner detection, and hacking from this old code of mine gives better results than off-the-shelf YOLOv(X).
Maybe if I have the motivation, will revamp this repo. Always useful to have a simple, hackable implementation lying around.

**Comment by artshcherbina** [comment]
I agree, understandability of the code is crucial to getting high performance.
Looking forward to your updates!
